import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

/**
 * Kapsamlı Türkçe karakter düzeltme sözlüğü.
 * Sıralama: daha uzun/spesifik formlar önce gelir (kısa kalıpları bozmaması için).
 * Her giriş: [regex, düzeltme]
 */
const FIXES: [RegExp, string][] = [
  // ─── Ü ───────────────────────────────────────────────
  [/\bYuksek\b/g,              "Yüksek"],
  [/\byuksek\b/g,              "yüksek"],
  [/\bYuksekligi\b/g,          "Yüksekliği"],
  [/\byuksekligi\b/g,          "yüksekliği"],
  [/\bguzelligiyle\b/g,        "güzelliğiyle"],
  [/\bguzelligi\b/g,           "güzelliği"],
  [/\bguzelliginden\b/g,       "güzelliğinden"],
  [/\bguzellik\b/g,            "güzellik"],
  [/\bguzel\b/g,               "güzel"],
  [/\bGuzelligi\b/g,           "Güzelliği"],
  [/\bGuzellik\b/g,            "Güzellik"],
  [/\bGuzel\b/g,               "Güzel"],
  [/\bgucunu\b/g,              "gücünü"],
  [/\bgucuyle\b/g,             "gücüyle"],
  [/\bguclu\b/g,               "güçlü"],
  [/\bGuclu\b/g,               "Güçlü"],
  [/\bGuc\b/g,                 "Güç"],
  [/\bguc\b/g,                 "güç"],
  [/\bgunluk\b/g,              "günlük"],
  [/\bGunluk\b/g,              "Günlük"],
  [/\bgunesli\b/g,             "güneşli"],
  [/\bgunes\b/g,               "güneş"],
  [/\bGunes\b/g,               "Güneş"],
  [/\bgunesin\b/g,             "güneşin"],
  [/\bgunu\b/g,                "günü"],
  [/\bgune\b/g,                "güne"],
  [/\bgunun\b/g,               "günün"],
  [/\bGunun\b/g,               "Günün"],
  [/\bgunumuzun\b/g,           "günümüzün"],
  [/\bguz\b/g,                 "güz"],
  [/\bGuz\b/g,                 "Güz"],
  [/\bogretici\b/g,            "öğretici"],
  [/\bogretim\b/g,             "öğretim"],
  [/\bunlu\b/g,                "ünlü"],
  [/\bUnlu\b/g,                "Ünlü"],
  [/\bunvani\b/g,              "ünvanı"],
  [/\bunvanini\b/g,            "ünvanını"],
  [/\bunvaniyla\b/g,           "ünvanıyla"],
  [/\bunvandan\b/g,            "ünvandan"],
  [/\bunvan\b/g,               "ünvan"],
  [/\bkulfet\b/g,              "külfet"],
  [/\bkucuk\b/g,               "küçük"],
  [/\bKucuk\b/g,               "Küçük"],
  [/\bkuresel\b/g,             "küresel"],
  [/\bkultur\b/g,              "kültür"],
  [/\bKultur\b/g,              "Kültür"],
  [/\bkulturun\b/g,            "kültürün"],
  [/\bkulturel\b/g,            "kültürel"],
  [/\bgururu\b/g,              "gururu"],  // bu zaten doğru
  [/\bbugun\b/g,               "bugün"],
  [/\bBugun\b/g,               "Bugün"],
  [/\btutunum\b/g,             "tutunumu"],
  [/\btutunumluluk\b/g,        "tutunumluluk"],
  [/\bkosullar\b/g,            "koşullar"],

  // ─── Ö ───────────────────────────────────────────────
  [/\bOzgun\b/g,               "Özgün"],
  [/\bozgun\b/g,               "özgün"],
  [/\bozgunlugu\b/g,           "özgünlüğü"],
  [/\bOzgunlugu\b/g,           "Özgünlüğü"],
  [/\bozgur\b/g,               "özgür"],
  [/\bOzgur\b/g,               "Özgür"],
  [/\bozgurluk\b/g,            "özgürlük"],
  [/\bOzgurluk\b/g,            "Özgürlük"],
  [/\bozgurlugu\b/g,           "özgürlüğü"],
  [/\bozgurce\b/g,             "özgürce"],
  [/\bOzel\b/g,                "Özel"],
  [/\bozel\b/g,                "özel"],
  [/\bozellik\b/g,             "özellik"],
  [/\bOzellik\b/g,             "Özellik"],
  [/\bozelligi\b/g,            "özelliği"],
  [/\bozellikleri\b/g,         "özellikleri"],
  [/\bozenle\b/g,              "özenle"],
  [/\bOzenle\b/g,              "Özenle"],
  [/\bozenli\b/g,              "özenli"],
  [/\bornekleri\b/g,           "örnekleri"],
  [/\borneklerinden\b/g,       "örneklerinden"],
  [/\bornegi\b/g,              "örneği"],
  [/\bornek\b/g,               "örnek"],
  [/\bOnde\b/g,                "Önde"],
  [/\bonde\b/g,                "önde"],
  [/\boner\b/g,                "öner"],
  [/\bonerileri\b/g,           "önerileri"],
  [/\boneri\b/g,               "öneri"],
  [/\bozet\b/g,                "özet"],
  [/\bodunsu\b/g,              "odunsu"],  // doğru

  // ─── Ş ───────────────────────────────────────────────
  [/\bsiirsel\b/g,             "şiirsel"],
  [/\bSiirsel\b/g,             "Şiirsel"],
  [/\bsiir\b/g,                "şiir"],
  [/\bSiir\b/g,                "Şiir"],
  [/\bsiklik\b/g,              "şıklık"],
  [/\bSiklik\b/g,              "Şıklık"],
  [/\bsikligi\b/g,             "şıklığı"],
  [/\bsekli\b/g,               "şekli"],
  [/\bsekilde\b/g,             "şekilde"],
  [/\bseklinde\b/g,            "şeklinde"],
  [/\bsekliyle\b/g,            "şekliyle"],
  [/\bsekillendi\b/g,          "şekillendi"],
  [/\bsaheser\b/g,             "şaheser"],
  [/\bSaheser\b/g,             "Şaheser"],
  [/\bsahane\b/g,              "şahane"],
  [/\bSahane\b/g,              "Şahane"],
  [/\bsarap\b/g,               "şarap"],
  [/\bSarap\b/g,               "Şarap"],
  [/\bseker\b/g,               "şeker"],
  [/\bSeker\b/g,               "Şeker"],
  [/\bsekerli\b/g,             "şekerli"],
  [/\bseker\b/g,               "şeker"],
  [/\bsefaf\b/g,               "şeffaf"],
  [/\bseffaf\b/g,              "şeffaf"],
  [/\bSeffaf\b/g,              "Şeffaf"],
  [/\bsimdi\b/g,               "şimdi"],
  [/\bSimdi\b/g,               "Şimdi"],
  [/\bsifali\b/g,              "şifalı"],
  [/\bsiddetli\b/g,            "şiddetli"],
  [/\bsiddeti\b/g,             "şiddeti"],
  [/\bsiddet\b/g,              "şiddet"],
  [/\bsinirlarini\b/g,         "sınırlarını"],
  [/\bsinirlarin\b/g,          "sınırların"],
  [/\bsinirlari\b/g,           "sınırları"],
  [/\bsinirlayan\b/g,          "sınırlayan"],
  [/\bsinirlandiran\b/g,       "sınırlandıran"],
  [/\bsiniri\b/g,              "sınırı"],
  [/\bsinirin\b/g,             "sınırın"],
  [/\bsinirdan\b/g,            "sınırdan"],
  [/\bsinir\b/g,               "sınır"],  // dikkatli: sinir = nerve DE olabilir ama parfüm bağlamında "sınır" daha yaygın
  [/\bsimgesi\b/g,             "simgesi"],  // bu doğru zaten
  [/\bScent\b/g,               "Scent"],    // İngilizce, dokunma
  [/\bsikayetci\b/g,           "şikayetçi"],
  [/\bsikayet\b/g,             "şikayet"],
  [/\bsans\b/g,                "şans"],
  [/\bSans\b/g,                "Şans"],
  [/\bsanli\b/g,               "şanlı"],
  [/\bsarki\b/g,               "şarkı"],
  [/\bSarki\b/g,               "Şarkı"],
  [/\bsarkisi\b/g,             "şarkısı"],
  [/\bsenfonisi\b/g,           "senfonisi"],  // doğru (senfoni = symphony)
  [/\bsikayeti\b/g,            "şikayeti"],
  [/\byansiyan\b/g,            "yansıyan"],
  [/\byasatan\b/g,             "yaşatan"],
  [/\bYasatan\b/g,             "Yaşatan"],
  [/\byasiyor\b/g,             "yaşıyor"],
  [/\byasam\b/g,               "yaşam"],
  [/\bYasam\b/g,               "Yaşam"],
  [/\byasami\b/g,              "yaşamı"],
  [/\byasayanlar\b/g,          "yaşayanlar"],
  [/\byasayan\b/g,             "yaşayan"],
  [/\byasadigimiz\b/g,         "yaşadığımız"],

  // ─── Ç ───────────────────────────────────────────────
  [/\bcagdas\b/g,              "çağdaş"],
  [/\bCagdas\b/g,              "Çağdaş"],
  [/\bcagdasi\b/g,             "çağdaşı"],
  [/\bcag\b/g,                 "çağ"],
  [/\bCag\b/g,                 "Çağ"],
  [/\bcagri\b/g,               "çağrı"],
  [/\bcagrisi\b/g,             "çağrısı"],
  [/\bcilek\b/g,               "çilek"],
  [/\bCilek\b/g,               "Çilek"],
  [/\bcileklerin\b/g,          "çileklerin"],
  [/\bcilegi\b/g,              "çileği"],
  [/\bcicegiyle\b/g,           "çiçeğiyle"],
  [/\bcicegin\b/g,             "çiçeğin"],
  [/\bciceksi\b/g,             "çiçeksi"],
  [/\bcicek\b/g,               "çiçek"],
  [/\bCicek\b/g,               "Çiçek"],
  [/\bcicegleri\b/g,           "çiçekleri"],
  [/\bciceklerin\b/g,          "çiçeklerin"],
  [/\bciceklerle\b/g,          "çiçeklerle"],
  [/\bcesitlilik\b/g,          "çeşitlilik"],
  [/\bcesitli\b/g,             "çeşitli"],
  [/\bCesitli\b/g,             "Çeşitli"],
  [/\bcesit\b/g,               "çeşit"],
  [/\bcevresel\b/g,            "çevresel"],
  [/\bcevre\b/g,               "çevre"],
  [/\bCevre\b/g,               "Çevre"],
  [/\bcogu\b/g,                "çoğu"],
  [/\bCogu\b/g,                "Çoğu"],
  [/\bcogunu\b/g,              "çoğunu"],
  [/\bcogunlukla\b/g,          "çoğunlukla"],
  [/\bcok\b/g,                 "çok"],
  [/\bCok\b/g,                 "Çok"],
  [/\bcoklu\b/g,               "çoklu"],
  [/\bcekici\b/g,              "çekici"],
  [/\bCekici\b/g,              "Çekici"],
  [/\bcekicilik\b/g,           "çekicilik"],
  [/\bcekiciligiyle\b/g,       "çekiciliğiyle"],
  [/\bcekiciligini\b/g,        "çekiciliğini"],
  [/\bcekiciligi\b/g,          "çekiciliği"],
  [/\bcekiciligi\b/g,          "çekiciliği"],
  [/\bcarpici\b/g,             "çarpıcı"],
  [/\bCarpici\b/g,             "Çarpıcı"],
  [/\bcagrisini\b/g,           "çağrısını"],
  [/\bcagriyi\b/g,             "çağrıyı"],
  [/\bcagrin\b/g,              "çağrın"],
  [/\bcifte\b/g,               "çifte"],
  [/\bcogu\b/g,                "çoğu"],
  [/\bcizgisi\b/g,             "çizgisi"],
  [/\bcizgisini\b/g,           "çizgisini"],
  [/\bcizgileriyle\b/g,        "çizgileriyle"],
  [/\bcizgi\b/g,               "çizgi"],
  [/\bcifti\b/g,               "çifti"],
  [/\bcift\b/g,                "çift"],
  [/\bcalisan\b/g,             "çalışan"],
  [/\bcalisma\b/g,             "çalışma"],
  [/\bcalismak\b/g,            "çalışmak"],
  [/\bcalis\b/g,               "çalış"],
  [/\bcikan\b/g,               "çıkan"],
  [/\bcikartici\b/g,           "çıkartıcı"],
  [/\bCikartici\b/g,           "Çıkartıcı"],
  [/\bcikis\b/g,               "çıkış"],
  [/\bciku\b/g,                "çıku"],  // olmayabilir
  [/\bcocuk\b/g,               "çocuk"],
  [/\bCocuk\b/g,               "Çocuk"],
  [/\bcoskullu\b/g,            "coşkulu"],
  [/\bCoskullu\b/g,            "Coşkulu"],
  [/\bcoskuyla\b/g,            "coşkuyla"],
  [/\bcosku\b/g,               "coşku"],
  [/\bCosku\b/g,               "Coşku"],
  [/\bcosmopolit\b/g,          "kozmopolit"],
  [/\bçekim\b/g,               "çekim"],  // zaten doğru

  // ─── Ğ ───────────────────────────────────────────────
  [/\bdegerlilik\b/g,          "değerlilik"],
  [/\bdegerli\b/g,             "değerli"],
  [/\bDegerli\b/g,             "Değerli"],
  [/\bdegeri\b/g,              "değeri"],
  [/\bdeger\b/g,               "değer"],
  [/\bDeger\b/g,               "Değer"],
  [/\bdegisik\b/g,             "değişik"],
  [/\bdegisim\b/g,             "değişim"],
  [/\bdegistiren\b/g,          "değiştiren"],
  [/\bdogaya\b/g,              "doğaya"],
  [/\bdogadan\b/g,             "doğadan"],
  [/\bdoganin\b/g,             "doğanın"],
  [/\bdogayla\b/g,             "doğayla"],
  [/\bdoga\b/g,                "doğa"],
  [/\bDoga\b/g,                "Doğa"],
  [/\bdogan\b/g,               "doğan"],
  [/\bDogan\b/g,               "Doğan"],
  [/\bDogu\b/g,                "Doğu"],
  [/\bdogu\b/g,                "doğu"],
  [/\bdogunun\b/g,             "doğunun"],
  [/\bDogulu\b/g,              "Doğulu"],
  [/\bdogulu\b/g,              "doğulu"],
  [/\bgelenegini\b/g,          "geleneğini"],
  [/\bgelenegi\b/g,            "geleneği"],
  [/\bgelenek\b/g,             "gelenek"],
  [/\bGelenek\b/g,             "Gelenek"],
  [/\bgorkeminin\b/g,          "görkemin"],
  [/\bgorkemini\b/g,           "görkemin"],
  [/\bgorkemli\b/g,            "görkemli"],
  [/\bGorkemli\b/g,            "Görkemli"],
  [/\bgorkemi\b/g,             "görkemi"],
  [/\bgorkemle\b/g,            "görkemle"],
  [/\bgorkem\b/g,              "görkem"],
  [/\bgorsel\b/g,              "görsel"],
  [/\byaraticiligindan\b/g,    "yaratıcılığından"],
  [/\byaraticiligiyle\b/g,     "yaratıcılığıyla"],
  [/\byaraticiligini\b/g,      "yaratıcılığını"],
  [/\byaraticiligi\b/g,        "yaratıcılığı"],
  [/\byaratijilik\b/g,         "yaratıcılık"],
  [/\byaratijiligini\b/g,      "yaratıcılığını"],
  [/\byaratici\b/g,            "yaratıcı"],
  [/\bYaratici\b/g,            "Yaratıcı"],
  [/\byaratilmis\b/g,          "yaratılmış"],
  [/\byaratilan\b/g,           "yaratılan"],
  [/\byaratilarak\b/g,         "yaratılarak"],
  [/\byolculugu\b/g,           "yolculuğu"],
  [/\byolculuguna\b/g,         "yolculuğuna"],
  [/\byolculugunuza\b/g,       "yolculuğunuza"],
  [/\bkaranlik\b/g,            "karanlık"],
  [/\bKaranlik\b/g,            "Karanlık"],
  [/\bkaranliga\b/g,           "karanlığa"],
  [/\bkaranligin\b/g,          "karanlığın"],
  [/\bogrenilen\b/g,           "öğrenilen"],

  // ─── I (dotless) ─────────────────────────────────────
  [/\bItalyan\b/g,             "İtalyan"],
  [/\bitalyan\b/g,             "İtalyan"],
  [/\bItalya\b/g,              "İtalya"],
  [/\bitalya\b/g,              "İtalya"],
  [/\bIngiliz\b/g,             "İngiliz"],
  [/\bingiliz\b/g,             "İngiliz"],
  [/\bIsvicre\b/g,             "İsviçre"],
  [/\bisvicre\b/g,             "İsviçre"],
  [/\bIspanya\b/g,             "İspanya"],
  [/\bispanya\b/g,             "İspanya"],
  [/\bIpek\b/g,                "İpek"],
  [/\bipek\b/g,                "ipek"],  // İpek = silk, küçük harfle de kullanılır
  [/\bIlham\b/g,               "İlham"],
  [/\bilham\b/g,               "ilham"],  // bu doğru
  [/\barasindaki\b/g,          "arasındaki"],
  [/\barasinda\b/g,            "arasında"],
  [/\bArasinda\b/g,            "Arasında"],
  [/\bsarayindan\b/g,          "sarayından"],
  [/\bsarayin\b/g,             "sarayın"],
  [/\bsarayinda\b/g,           "sarayında"],
  [/\bkalici\b/g,              "kalıcı"],
  [/\bKalici\b/g,              "Kalıcı"],
  [/\bkaliciligi\b/g,          "kalıcılığı"],
  [/\bkaliciligiyle\b/g,       "kalıcılığıyla"],
  [/\baltin\b/g,               "altın"],
  [/\bAltin\b/g,               "Altın"],
  [/\baltindan\b/g,            "altından"],
  [/\baltinla\b/g,             "altınla"],
  [/\bsicakligini\b/g,         "sıcaklığını"],
  [/\bsicakligi\b/g,           "sıcaklığı"],
  [/\bsicakligiyla\b/g,        "sıcaklığıyla"],
  [/\bsicaklik\b/g,            "sıcaklık"],
  [/\bSicaklik\b/g,            "Sıcaklık"],
  [/\bsicak\b/g,               "sıcak"],
  [/\bSicak\b/g,               "Sıcak"],
  [/\bkorfez\b/g,              "körfez"],
  [/\bKorfez\b/g,              "Körfez"],
  [/\bkorfezin\b/g,            "körfezin"],
  [/\bkorfezi\b/g,             "körfezi"],
  [/\bzanaaatciliginin\b/g,    "zanaatçılığının"],
  [/\bzanaaatciligini\b/g,     "zanaatçılığını"],
  [/\bzanaatciligini\b/g,      "zanaatçılığını"],
  [/\bzanaatciliginin\b/g,     "zanaatçılığının"],
  [/\bzanaaatciligine\b/g,     "zanaatçılığına"],
  [/\bzanaatciligine\b/g,      "zanaatçılığına"],
  [/\bustaliginin\b/g,         "ustalığının"],
  [/\bustaligini\b/g,          "ustalığını"],
  [/\bustaliginden\b/g,        "ustalığından"],
  [/\bustaligiyla\b/g,         "ustalığıyla"],
  [/\bustaliginde\b/g,         "ustalığında"],
  [/\bustaligine\b/g,          "ustalığına"],
  [/\bustalik\b/g,             "ustalık"],
  [/\bUstalik\b/g,             "Ustalık"],
  [/\byapimi\b/g,              "yapımı"],
  [/\bYapimi\b/g,              "Yapımı"],
  [/\byapiminda\b/g,           "yapımında"],
  [/\byapimiyla\b/g,           "yapımıyla"],
  [/\bimzasini\b/g,            "imzasını"],
  [/\bmirasini\b/g,            "mirasını"],
  [/\banlayisini\b/g,          "anlayışını"],
  [/\banlayisi\b/g,            "anlayışı"],
  [/\banlayisiyla\b/g,         "anlayışıyla"],
  [/\byapiyla\b/g,             "yapıyla"],
  [/\byapisi\b/g,              "yapısı"],
  [/\byapisin\b/g,             "yapısın"],
  [/\bbildiginiz\b/g,          "bildiğiniz"],
  [/\bbildiginize\b/g,         "bildiğinize"],
  [/\bnotalari\b/g,            "notaları"],
  [/\bkayali\b/g,              "kayalı"],  // kayalı doğru olabilir (rocky)
  [/\balinarak\b/g,            "alınarak"],
  [/\bAlınarak\b/g,            "Alınarak"],
  [/\btaninan\b/g,             "tanınan"],
  [/\btanimli\b/g,             "tanımlı"],
  [/\btaninmis\b/g,            "tanınmış"],
  [/\btaninmis\b/g,            "tanınmış"],
  [/\bkopruyu\b/g,             "köprüyü"],
  [/\bkopru\b/g,               "köprü"],
  [/\bkuran\b/g,               "kuran"],  // Dikkat: Kuran (kitap) vs kuran (kurmak fiili) - bağlama göre
  [/\bduyularinizi\b/g,        "duyularınızı"],
  [/\bduyularini\b/g,          "duyularını"],
  [/\bduyulariniz\b/g,         "duyularınız"],
  [/\bduyulariniza\b/g,        "duyularınıza"],
  [/\bhammaddeleriyle\b/g,     "hammaddeleriyle"],  // doğru
  [/\bhassasiyetini\b/g,       "hassasiyetini"],    // doğru
  [/\bserisinden\b/g,          "serisinden"],        // doğru
  [/\bserisinin\b/g,           "serisinin"],         // doğru
  [/\bsunulmak\b/g,            "sunulmak"],          // doğru
  [/\bdunyasinin\b/g,          "dünyasının"],
  [/\bDunyasinin\b/g,          "Dünyasının"],
  [/\bdunyayi\b/g,             "dünyayı"],
  [/\bdunyaya\b/g,             "dünyaya"],
  [/\bdunyada\b/g,             "dünyada"],
  [/\bdunyanin\b/g,            "dünyanın"],
  [/\bDunyanin\b/g,            "Dünyanın"],
  [/\bdunyasindan\b/g,         "dünyasından"],
  [/\bdunyasini\b/g,           "dünyasını"],
  [/\bdunyasindan\b/g,         "dünyasından"],
  [/\bdunyasi\b/g,             "dünyası"],
  [/\bdunyasiyla\b/g,          "dünyasıyla"],
  [/\bDunya\b/g,               "Dünya"],
  [/\bdunya\b/g,               "dünya"],
  [/\bbaslayan\b/g,            "başlayan"],
  [/\bBaslayan\b/g,            "Başlayan"],
  [/\bbaslayan\b/g,            "başlayan"],
  [/\bbaslangic\b/g,           "başlangıç"],
  [/\bBaslangic\b/g,           "Başlangıç"],
  [/\bbaslatir\b/g,            "başlatır"],
  [/\bbashlamis\b/g,           "başlamış"],
  [/\bbaslamis\b/g,            "başlamış"],
  [/\bbasinda\b/g,             "başında"],
  [/\bbasin\b/g,               "başın"],
  [/\bbasi\b/g,                "başı"],
  [/\bbasatan\b/g,             "başlatan"],  // "basatan" → "başlatan" ya da "başatan"?
  [/\btasimayan\b/g,           "taşımayan"],
  [/\btasimaktadir\b/g,        "taşımaktadır"],
  [/\btasiyan\b/g,             "taşıyan"],
  [/\btasir\b/g,               "taşır"],
  [/\btasimak\b/g,             "taşımak"],
  [/\btasinan\b/g,             "taşınan"],
  [/\btasimaktadir\b/g,        "taşımaktadır"],
  [/\btasinmis\b/g,            "taşınmış"],
  [/\btazelik\b/g,             "tazelik"],    // doğru
  [/\btazeligi\b/g,            "tazeliği"],
  [/\btazeligiyle\b/g,         "tazeliğiyle"],
  [/\byansitan\b/g,            "yansıtan"],
  [/\bYansitan\b/g,            "Yansıtan"],
  [/\byansitir\b/g,            "yansıtır"],
  [/\byansitarak\b/g,          "yansıtarak"],
  [/\byansitilan\b/g,          "yansıtılan"],
  [/\bsurelidir\b/g,           "sürelidir"],
  [/\bsureli\b/g,              "süreli"],
  [/\bsure\b/g,                "süre"],
  [/\bSure\b/g,                "Süre"],
  [/\bsuzulen\b/g,             "süzülen"],
  [/\bsuzulerek\b/g,           "süzülerek"],
  [/\bmodernligini\b/g,        "modernliğini"],
  [/\bmodernligi\b/g,          "modernliği"],
  [/\bmodernligiyle\b/g,       "modernliğiyle"],
  [/\bmodernlik\b/g,           "modernlik"],
  [/\bbilesenleriyle\b/g,      "bileşenleriyle"],
  [/\bbilesenler\b/g,          "bileşenler"],
  [/\bbileseni\b/g,            "bileşeni"],
  [/\bbilesen\b/g,             "bileşen"],
  [/\bparfumerinin\b/g,        "parfümerinin"],
  [/\bparfumerisi\b/g,         "parfümerisi"],
  [/\bparfumeri\b/g,           "parfümeri"],
  [/\bparfumdur\b/g,           "parfümdür"],
  [/\bparfumun\b/g,            "parfümün"],
  [/\bparfumu\b/g,             "parfümü"],
  [/\bparfumde\b/g,            "parfümde"],
  [/\bparfum\b/g,              "parfüm"],
  [/\bParfumun\b/g,            "Parfümün"],
  [/\bParfum\b/g,              "Parfüm"],
  [/\bluksunun\b/g,            "lüksünün"],
  [/\bluksunu\b/g,             "lüksünü"],
  [/\bluksle\b/g,              "lüksle"],
  [/\bLuks\b/g,                "Lüks"],
  [/\bluks\b/g,                "lüks"],
  [/\bseçilmistir\b/g,         "seçilmiştir"],  // ç zaten var ama ş eksik
  [/\bsecilmistir\b/g,         "seçilmiştir"],
  [/\bsecilmis\b/g,            "seçilmiş"],
  [/\bsecilen\b/g,             "seçilen"],
  [/\bsecilmis\b/g,            "seçilmiş"],
  [/\bseckin\b/g,              "seçkin"],
  [/\bSeckin\b/g,              "Seçkin"],
  [/\bsec\b/g,                 "seç"],
  [/\bdurumu\b/g,              "durumu"],   // doğru
  [/\bFransiz\b/g,             "Fransız"],
  [/\bfransiz\b/g,             "Fransız"],
  [/\bFransa\b/g,              "Fransa"],   // doğru
  [/\bdonemi\b/g,              "dönemi"],
  [/\bDonem\b/g,               "Dönem"],
  [/\bdonem\b/g,               "dönem"],
  [/\bdonusturulen\b/g,        "dönüştürülen"],
  [/\bdonusturen\b/g,          "dönüştüren"],
  [/\bdonusturmek\b/g,         "dönüştürmek"],
  [/\bdonusum\b/g,             "dönüşüm"],
  [/\bbulustiran\b/g,          "buluşturan"],
  [/\bbulusturan\b/g,          "buluşturan"],
  [/\byapiyla\b/g,             "yapıyla"],
  [/\byaratilmis\b/g,          "yaratılmış"],
  [/\byaratilarak\b/g,         "yaratılarak"],
  [/\bsehir\b/g,               "şehir"],
  [/\bSehir\b/g,               "Şehir"],
  [/\bsehrin\b/g,              "şehrin"],
  [/\bsehirde\b/g,             "şehirde"],
  [/\bsehirlerin\b/g,          "şehirlerin"],
  [/\bkosullarinda\b/g,        "koşullarında"],
  [/\bkosullarda\b/g,          "koşullarda"],
  [/\bkosullar\b/g,            "koşullar"],
  [/\bkosul\b/g,               "koşul"],
  [/\bserefine\b/g,            "şerefine"],
  [/\bseref\b/g,               "şeref"],
  [/\bsimgelemektedir\b/g,     "simgelemektedir"],  // doğru
  [/\bsimgeliyor\b/g,          "simgeliyor"],        // doğru
  [/\bsimgeleyen\b/g,          "simgeleyen"],        // doğru
  [/\bsimgeler\b/g,            "simgeler"],          // doğru
  [/\bkeskince\b/g,            "keskinliğiyle"],
  [/\bkeskinligiyle\b/g,       "keskinliğiyle"],
  [/\bkeskinligi\b/g,          "keskinliği"],
  [/\bkeskin\b/g,              "keskin"],   // doğru
  [/\bkiskirtici\b/g,          "kışkırtıcı"],
  [/\bkiskirticilik\b/g,       "kışkırtıcılık"],
  [/\bgizemiyle\b/g,           "giziyle"],   // "gizemiyle" zaten doğru
  [/\botoritesini\b/g,         "otoritesini"],   // doğru
  [/\bkusursuz\b/g,            "kusursuz"],      // doğru
  [/\bserinligi\b/g,           "serinliği"],
  [/\bserinligiyle\b/g,        "serinliğiyle"],
  [/\bserinligini\b/g,         "serinliğini"],
  [/\bserinletici\b/g,         "serinletici"],   // doğru
  [/\bserinlik\b/g,            "serinlik"],      // doğru
  [/\bserinligi\b/g,           "serinliği"],
  [/\btutkunun\b/g,            "tutkunun"],      // doğru
  [/\btutku\b/g,               "tutku"],         // doğru
  [/\byogun\b/g,               "yoğun"],
  [/\bYogun\b/g,               "Yoğun"],
  [/\byogunlugu\b/g,           "yoğunluğu"],
  [/\byogunluk\b/g,            "yoğunluk"],
  [/\bzariflik\b/g,            "zariflik"],      // doğru
  [/\bzarafeti\b/g,            "zarafeti"],      // doğru
  [/\benginin\b/g,             "enginin"],        // doğru? (engin = vast)
  [/\bengel\b/g,               "engel"],          // doğru
  [/\bsembohu\b/g,             "simgesi"],
  [/\bsemin\b/g,               "şemin"],   // olmayabilir
  [/\bgosterisi\b/g,           "gösterisi"],
  [/\bgosterisini\b/g,         "gösterisini"],
  [/\bgosteri\b/g,             "gösteri"],
  [/\bgosteriyor\b/g,          "gösteriyor"],
  [/\bgosterilemez\b/g,        "gösterilemez"],
  [/\bgosterileri\b/g,         "gösterileri"],
  [/\bgorkemin\b/g,            "görkemin"],      // zaten doğru
  [/\bgorunum\b/g,             "görünüm"],
  [/\bgorunumu\b/g,            "görünümü"],
  [/\bgoruntu\b/g,             "görüntü"],
  [/\bgoruntuu\b/g,            "görüntüsü"],
  [/\bboyle\b/g,               "böyle"],
  [/\bBoyle\b/g,               "Böyle"],
  [/\bboylelikle\b/g,          "böylelikle"],
  [/\bonce\b/g,                "önce"],
  [/\bOnce\b/g,                "Önce"],
  [/\bonceki\b/g,              "önceki"],
  [/\boncelikle\b/g,           "öncelikle"],
  [/\boncelik\b/g,             "öncelik"],
  [/\butku\b/g,                "ütkü"],   // olmayabilir
  [/\burun\b/g,                "ürün"],
  [/\bUrun\b/g,                "Ürün"],
  [/\burunun\b/g,              "ürünün"],
  [/\burunler\b/g,             "ürünler"],
  [/\burunleri\b/g,            "ürünleri"],
  [/\burunun\b/g,              "ürünün"],
  [/\bmusterilerin\b/g,        "müşterilerin"],
  [/\bmusteri\b/g,             "müşteri"],
  [/\bMusterilerin\b/g,        "Müşterilerin"],
  [/\bMusteriye\b/g,           "Müşteriye"],
  [/\bgosterisi\b/g,           "gösterisi"],

  // ─── Kaçan ek kelimeler ──────────────────────────────
  [/\bestetigini\b/g,          "estetiğini"],
  [/\bestetegiyle\b/g,         "estetiğiyle"],
  [/\bestetigi\b/g,            "estetiği"],
  [/\bEstetigi\b/g,            "Estetiği"],
  [/\bestetik\b/g,             "estetik"],   // doğru
  [/\btasarimlarini\b/g,       "tasarımlarını"],
  [/\btasarimlariyla\b/g,      "tasarımlarıyla"],
  [/\btasarimlariyla\b/g,      "tasarımlarıyla"],
  [/\btasarimlari\b/g,         "tasarımları"],
  [/\btasariminda\b/g,         "tasarımında"],
  [/\btasarimimiyla\b/g,       "tasarımımıyla"],
  [/\btasarimiyla\b/g,         "tasarımıyla"],
  [/\btasarimi\b/g,            "tasarımı"],
  [/\btasarim\b/g,             "tasarım"],
  [/\bTasarim\b/g,             "Tasarım"],
  [/\bkokusunu\b/g,            "kokusunu"],    // doğru
  [/\benerjisiyle\b/g,         "enerjisiyle"], // doğru
  [/\bkarmasiyla\b/g,          "karmaşıyla"],
  [/\bkarmasi\b/g,             "karmaşı"],
  [/\bkarmasik\b/g,            "karmaşık"],
  [/\bKarmasik\b/g,            "Karmaşık"],
  [/\bkoruyucu\b/g,            "koruyucu"],    // doğru
  [/\buyumlu\b/g,              "uyumlu"],      // doğru
  [/\buyumunu\b/g,             "uyumunu"],     // doğru
  [/\bdigerlerinden\b/g,       "diğerlerinden"],
  [/\bdigerlerine\b/g,         "diğerlerine"],
  [/\bdigerleri\b/g,           "diğerleri"],
  [/\bdigeri\b/g,              "diğeri"],
  [/\bdiger\b/g,               "diğer"],
  [/\bDiger\b/g,               "Diğer"],
  [/\bbirlesik\b/g,            "birleşik"],
  [/\bbirlesiyor\b/g,          "birleşiyor"],
  [/\bbirlesen\b/g,            "birleşen"],
  [/\bbirlesimi\b/g,           "birleşimi"],
  [/\bbirlesim\b/g,            "birleşim"],
  [/\bbirlestirir\b/g,         "birleştirir"],
  [/\bbirlestiren\b/g,         "birleştiren"],
];

function applyFixes(text: string | null): string | null {
  if (!text) return text;
  let out = text;
  for (const [re, replacement] of FIXES) {
    out = out.replace(re, replacement);
  }
  return out;
}

async function main() {
  const products = await prisma.product.findMany({
    where: { deletedAt: null },
    select: { id: true, name: true, description: true },
  });

  console.log(`Toplam ürün: ${products.length}`);

  let updated = 0;
  for (const p of products) {
    const fixed = applyFixes(p.description);
    if (fixed !== p.description) {
      await prisma.product.update({
        where: { id: p.id },
        data: { description: fixed },
      });
      updated++;
      if (updated <= 5) {
        console.log(`\n✓ ${p.name}`);
        // Farkı göster
        const orig = p.description ?? "";
        const words1 = orig.split(/\s+/);
        const words2 = (fixed ?? "").split(/\s+/);
        const diffs: string[] = [];
        for (let i = 0; i < words1.length; i++) {
          if (words1[i] !== words2[i]) diffs.push(`  ${words1[i]} → ${words2[i]}`);
        }
        diffs.slice(0, 6).forEach((d) => console.log(d));
      }
    }
  }

  console.log(`\n✅ Toplam güncellenen: ${updated} / ${products.length} ürün`);
  await prisma.$disconnect();
}

main().catch((e) => { console.error(e.message); process.exit(1); });
